### ISSUE TITLE
GPIOxx_IN

### ISSUE THREAD

**Issue by k-a-z-u** [maowen/esp8266_fast_gpio#2]
When accessing e.g. GPIO12_IN, I receive the following error:
right shift count >= width of type [-Werror]
 #define BIT12   0x00001000
                 ^

I guess GPIO12_IN (and others) should read
#define GPIO12_IN        (GPIO_INPUT_GET(12))
instead of
#define GPIO12_IN        (GPIO_INPUT_GET(BIT12))
?

**Comment by maowen** [comment]
Thanks for submitting a ticket. I had found this bug when using these macros for my own projects but I forgot to push it to github. It's now fixed.
