### ISSUE TITLE
GPIO0_CONF

### ISSUE THREAD

**Issue by k-a-z-u** [maowen/esp8266_fast_gpio#3]
reads
#define GPIO0_CONF      (PIN_FUNC_SELECT(GPIO0_MUX, FUNC_GPIO0))
but should probably read
#define GPIO0_CONF      PIN_FUNC_SELECT(GPIO0_MUX, FUNC_GPIO0)
like all others do?

**Comment by maowen** [comment]
I added the parentheses to all `GPIOX_CONF` macros for better macro style/safety
